# Supabase Configuration
SUPABASE_URL = "https://jmyqirpxiyxfwxpisyhu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpteXFpcnB4aXl4Znd4cGlzeWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTM2ODcsImV4cCI6MjA2ODY2OTY4N30.KDiPhEyUknH8lr5o-hLw6_YwdEBUf1zTeppTyey7Kho"